/* Mock data for entire app: history, templates, summaries, sharing */

window.HISTORY = [
  {
    id: "m-aviv-3",
    client: "Aviv Capital",
    title: "Vertex AI Migration · Technical deep-dive",
    date: "Apr 24, 2026",
    dateISO: "2026-04-24",
    time: "14:00",
    duration: "47m",
    rep: "Noa Levi",
    stage: "Discovery",
    score: 86,
    sentiment: "positive",
    tags: ["Vertex AI", "Bedrock", "Latency"],
    hintCount: 14,
    actedOn: 9,
    nextStep: "Send regional latency benchmark · due Apr 28",
    avatar: "#EA4335",
    participants: [
      { name: "Yael Ben-David", role: "VP Eng", initials: "YB", color: "#EA4335" },
      { name: "Daniel Cohen", role: "Staff ML", initials: "DC", color: "#F9AB00" },
      { name: "Noa Levi", role: "SuperCloud", initials: "NL", color: "#1A73E8" },
    ],
  },
  {
    id: "m-rapyd-2",
    client: "Rapyd Labs",
    title: "BigQuery + Looker discovery",
    date: "Apr 23, 2026",
    dateISO: "2026-04-23",
    time: "10:30",
    duration: "38m",
    rep: "Noa Levi",
    stage: "Qualification",
    score: 72,
    sentiment: "neutral",
    tags: ["BigQuery", "Looker", "Data warehouse"],
    hintCount: 9,
    actedOn: 6,
    nextStep: "Loop in data team · proposal Apr 30",
    avatar: "#1A73E8",
    participants: [
      { name: "Amit Shaked", role: "Head of Data", initials: "AS", color: "#34A853" },
      { name: "Lena Roth", role: "Data Eng Lead", initials: "LR", color: "#9B59B6" },
      { name: "Noa Levi", role: "SuperCloud", initials: "NL", color: "#1A73E8" },
    ],
    sharedBy: { name: "Tomer Avraham", initials: "TA", color: "#EA4335", role: "Sales Manager" },
    sharedAt: "2 days ago",
  },
  {
    id: "m-monday-7",
    client: "Monday.com",
    title: "GKE Autopilot follow-up",
    date: "Apr 22, 2026",
    dateISO: "2026-04-22",
    time: "16:00",
    duration: "29m",
    rep: "Noa Levi",
    stage: "Negotiation",
    score: 91,
    sentiment: "buying",
    tags: ["GKE", "Autopilot", "Cost"],
    hintCount: 11,
    actedOn: 10,
    nextStep: "MSA review with legal",
    avatar: "#34A853",
    participants: [
      { name: "Roy Maor", role: "VP Platform", initials: "RM", color: "#34A853" },
      { name: "Tal Grinberg", role: "SRE Lead", initials: "TG", color: "#EA4335" },
      { name: "Noa Levi", role: "SuperCloud", initials: "NL", color: "#1A73E8" },
    ],
    sharedBy: { name: "Eitan Shapira", initials: "ES", color: "#F9AB00", role: "AE — Fintech" },
    sharedAt: "5 days ago",
  },
  {
    id: "m-wix-1",
    client: "Wix",
    title: "First introduction — AI infra",
    date: "Apr 21, 2026",
    dateISO: "2026-04-21",
    time: "09:00",
    duration: "32m",
    rep: "Noa Levi",
    stage: "Intro",
    score: 64,
    sentiment: "neutral",
    tags: ["Gemini", "Vertex"],
    hintCount: 7,
    actedOn: 4,
    nextStep: "Share Gemini Flash benchmark",
    avatar: "#F9AB00",
    participants: [
      { name: "Matan Bordo", role: "Dir. AI Platform", initials: "MB", color: "#F9AB00" },
      { name: "Noa Levi", role: "SuperCloud", initials: "NL", color: "#1A73E8" },
    ],
  },
  {
    id: "m-aviv-2",
    client: "Aviv Capital",
    title: "Discovery call — algo trading desk",
    date: "Apr 14, 2026",
    dateISO: "2026-04-14",
    time: "11:00",
    duration: "52m",
    rep: "Noa Levi",
    stage: "Discovery",
    score: 78,
    sentiment: "positive",
    tags: ["Vertex AI", "Cost", "Bedrock"],
    hintCount: 12,
    actedOn: 8,
    nextStep: "Schedule technical follow-up",
    avatar: "#EA4335",
    participants: [
      { name: "Yael Ben-David", role: "VP Eng", initials: "YB", color: "#EA4335" },
      { name: "Oren Gilad", role: "Head of Algo Trading", initials: "OG", color: "#34A853" },
      { name: "Noa Levi", role: "SuperCloud", initials: "NL", color: "#1A73E8" },
    ],
  },
  {
    id: "m-pagaya-1",
    client: "Pagaya",
    title: "Cloud Spanner + Vertex briefing",
    date: "Apr 18, 2026",
    dateISO: "2026-04-18",
    time: "13:30",
    duration: "41m",
    rep: "Noa Levi",
    stage: "Discovery",
    score: 80,
    sentiment: "positive",
    tags: ["Spanner", "Vertex"],
    hintCount: 10,
    actedOn: 7,
    nextStep: "Architecture review next week",
    avatar: "#1A73E8",
    participants: [
      { name: "Adi Navon", role: "CTO", initials: "AN", color: "#1A73E8" },
      { name: "Tali Frenkel", role: "Eng Manager", initials: "TF", color: "#9B59B6" },
      { name: "Noa Levi", role: "SuperCloud", initials: "NL", color: "#1A73E8" },
    ],
  },
];

window.TEAM = [
  { name: "Noa Levi",       role: "Sr. Cloud SE",        initials: "NL", color: "#1A73E8", you: true,  email: "noalevi@google.com" },
  { name: "Tomer Avraham",  role: "Sales Manager",       initials: "TA", color: "#EA4335",            email: "tavraham@google.com" },
  { name: "Maya Stern",     role: "Customer Engineer",   initials: "MS", color: "#34A853",            email: "mstern@google.com" },
  { name: "Eitan Shapira",  role: "AE — Fintech",        initials: "ES", color: "#F9AB00",            email: "eitans@google.com" },
  { name: "Lior Aviv",      role: "Solutions Architect", initials: "LA", color: "#1A73E8",            email: "lioraviv@google.com" },
  { name: "Yoni Karmeli",   role: "SE Manager",           initials: "YK", color: "#EA4335",            email: "ykarmeli@google.com" },
  { name: "Daria Kogan",    role: "AE — Enterprise",     initials: "DK", color: "#9B59B6",            email: "dkogan@google.com" },
  { name: "Roi Halfon",     role: "Cloud SE",             initials: "RH", color: "#34A853",            email: "rhalfon@google.com" },
  { name: "Shir Ben-Ari",   role: "AE — Mid-market",      initials: "SB", color: "#F9AB00",            email: "shirba@google.com" },
  { name: "Idan Peretz",    role: "Solutions Architect", initials: "IP", color: "#1A73E8",            email: "ipperetz@google.com" },
  { name: "Galia Mor",      role: "AE — Strategic",       initials: "GM", color: "#EA4335",            email: "galiamor@google.com" },
  { name: "Avi Bar",        role: "Customer Engineer",   initials: "AB", color: "#9B59B6",            email: "avibar@google.com" },
];

window.SUMMARIES = {
  "m-aviv-3": {
    meeting: {
      client: "Aviv Capital",
      title: "Vertex AI Migration · Technical deep-dive",
      date: "Apr 24, 2026",
      duration: "47 minutes",
      avatar: "#EA4335",
      participants: ["Yael Ben-David (VP Eng)", "Daniel Cohen (Staff ML)", "Noa Levi (SuperCloud)"],
    },
    internal: {
      confidence: 0.78,
      health: "warm",
      score: 86,
      wentWell: [
        "Reframed Bedrock spend conversation around Model Garden — client engaged immediately.",
        "Surfaced regional endpoints (europe-west4) at the right moment when latency pain was admitted.",
        "Caught the buying signal at 22:34 and pivoted to procurement timeline.",
      ],
      couldImprove: [
        "Did not probe deeply enough on existing AWS contractual commitments — risk of co-existence.",
        "Skipped competitive Anthropic-on-Bedrock pricing comparison; would have strengthened the cost narrative.",
        "Missed opportunity to ask about VPC-SC / CMEK requirements after security mention.",
      ],
      upsell: [
        { name: "Vertex AI Pipelines", reason: "Daniel mentioned manual model promotion across teams — ~$14K/mo expansion." },
        { name: "BigQuery ML",         reason: "Trading-signal team currently exports to Snowflake — clean migration path." },
        { name: "Cloud Armor + WAF",   reason: "Compliance posture mentioned 3× — security upsell warm." },
      ],
      risks: [
        "Existing Bedrock commitment unclear — could delay POC start.",
        "Yael flagged board pressure for Q2 — aggressive timeline risk.",
      ],
      needs: {
        stated: ["Lower latency from EU", "Multi-model flexibility", "Cost predictability"],
        actual: ["Architectural escape hatch from AWS", "Better governance for risk team", "Q2 board win"],
      },
      actionItems: [
        { who: "Noa",    what: "Send latency benchmark for europe-west4 vs us-east-1",            due: "Apr 28" },
        { who: "Noa",    what: "Loop in Lior on architecture review",                              due: "Apr 30" },
        { who: "Maya",   what: "Prepare Model Garden + Anthropic-on-Vertex pricing comparison",   due: "May 2"  },
        { who: "Yael",   what: "Share existing AWS commitment terms",                              due: "Apr 30" },
      ],
    },
    client: {
      subject: "Recap — Vertex AI migration discussion (Apr 24)",
      greeting: "Hi Yael, Daniel,",
      body: [
        "Thank you for the detailed conversation today. Quick recap of what we discussed and the next steps we agreed on.",
        "**Discussion summary**\nWe walked through your current model serving setup on AWS Bedrock and the latency challenges you're seeing for European traders (1.8–2.2s p95). We aligned on the value of evaluating Vertex AI Model Garden as a path to consolidate Anthropic, Google, and open-source models behind a single endpoint with regional deployment in europe-west4.",
        "**Key topics covered**\n• Current state: ~$38K/month inference spend on Claude Sonnet via Bedrock\n• Latency requirements: sub-1s p95 for trading workflows\n• Multi-team versioning challenges between research and risk\n• Compliance posture: VPC-SC and CMEK requirements",
        "**Next steps**\n• I will send a latency benchmark comparing europe-west4 to your current us-east-1 setup by Apr 28.\n• Maya from our team will prepare a pricing comparison for Model Garden vs. your current Bedrock spend by May 2.\n• You agreed to share your current AWS commitment terms so we can plan the migration window appropriately.\n• We will schedule a technical architecture review with Lior, our solutions architect, for the week of May 5.",
        "Looking forward to continuing the conversation. Please don't hesitate to reach out with any questions in the meantime.",
      ],
      signoff: "Best,\nNoa Levi\nSr. Cloud SE — SuperCloud",
    },
    references: [
      { title: "Vertex AI Model Garden — overview",                href: "https://cloud.google.com/model-garden",                          source: "cloud.google.com" },
      { title: "Anthropic Claude on Vertex AI",                     href: "https://cloud.google.com/vertex-ai/generative-ai/docs/partner-models/claude", source: "cloud.google.com" },
      { title: "Regional endpoints for Vertex AI (europe-west4)",   href: "https://cloud.google.com/vertex-ai/docs/general/locations",      source: "cloud.google.com" },
      { title: "Vertex AI pricing & committed-use discounts",       href: "https://cloud.google.com/vertex-ai/pricing",                     source: "cloud.google.com" },
      { title: "Provisioned throughput for Generative AI",          href: "https://cloud.google.com/vertex-ai/generative-ai/docs/provisioned-throughput", source: "cloud.google.com" },
      { title: "Customer story — low-latency inference in EU",      href: "https://cloud.google.com/customers",                              source: "cloud.google.com" },
    ],
  },

  "m-rapyd-2": {
    meeting: {
      client: "Rapyd Labs",
      title: "BigQuery + Looker discovery",
      date: "Apr 23, 2026",
      duration: "38 minutes",
      avatar: "#1A73E8",
      participants: ["Amit Shaked (Head of Data)", "Lena Roth (Data Eng Lead)", "Noa Levi (SuperCloud)"],
    },
    internal: {
      confidence: 0.65,
      health: "cool",
      score: 72,
      wentWell: [
        "Quickly identified the pain around Snowflake query costs — $52K/mo spend resonated.",
        "Positioned BigQuery's serverless model as operational simplification, not just cost savings.",
        "Good rapport with Amit — he's clearly the internal champion.",
      ],
      couldImprove: [
        "Lena was skeptical about migration effort — should have addressed dbt compatibility earlier.",
        "Did not explore their existing Looker usage depth — unclear if they need Looker Studio or full Looker.",
        "Missed chance to ask about real-time streaming needs (Kafka/Pub Sub).",
      ],
      upsell: [
        { name: "Dataform",          reason: "Lena mentioned heavy dbt usage — Dataform is a natural fit." },
        { name: "Looker Embedded",   reason: "Amit hinted at customer-facing dashboards — embedded analytics play." },
      ],
      risks: [
        "Snowflake contract runs until Q4 — limited urgency for migration.",
        "Data eng team is small (4 people) — migration capacity concern.",
      ],
      needs: {
        stated: ["Lower query costs", "Better BI tooling", "Reduce ops overhead"],
        actual: ["Consolidate fragmented data stack", "Enable self-serve analytics for product team", "Justify data platform investment to CFO"],
      },
      actionItems: [
        { who: "Noa",    what: "Send BigQuery vs Snowflake TCO comparison for their workload profile",  due: "Apr 28" },
        { who: "Noa",    what: "Schedule Looker demo with their product analytics team",                  due: "May 1"  },
        { who: "Amit",   what: "Share current Snowflake usage metrics and top 20 queries",                due: "Apr 30" },
        { who: "Maya",   what: "Prepare dbt-to-Dataform migration guide",                                 due: "May 5"  },
      ],
    },
    client: {
      subject: "Recap — BigQuery + Looker discovery (Apr 23)",
      greeting: "Hi Amit, Lena,",
      body: [
        "Great meeting today — thanks for walking us through your current data stack. Here's a quick summary of what we covered.",
        "**Discussion summary**\nWe reviewed your current Snowflake-based data warehouse setup and the cost pressures you're experiencing at ~$52K/mo. We discussed how BigQuery's serverless, pay-per-query model could reduce costs while simplifying operations for your lean data team.",
        "**Key topics covered**\n• Current Snowflake spend: ~$52K/month with growing query volumes\n• BI tooling: currently using a mix of Metabase and custom dashboards\n• Data pipeline: dbt-based transformation layer\n• Team capacity: 4-person data eng team managing all pipelines",
        "**Next steps**\n• I'll prepare a TCO comparison tailored to your workload profile by Apr 28.\n• We'll schedule a hands-on Looker demo with your product analytics team for early May.\n• Amit, if you can share your current usage metrics and top queries, that will help us model the cost comparison accurately.",
        "Looking forward to the next steps. Happy to jump on a quick call if any questions come up.",
      ],
      signoff: "Best,\nNoa Levi\nSr. Cloud SE — SuperCloud",
    },
    references: [
      { title: "BigQuery overview",                    href: "https://cloud.google.com/bigquery",                    source: "cloud.google.com" },
      { title: "BigQuery pricing",                      href: "https://cloud.google.com/bigquery/pricing",            source: "cloud.google.com" },
      { title: "Looker overview",                       href: "https://cloud.google.com/looker",                      source: "cloud.google.com" },
      { title: "Dataform — SQL workflow",               href: "https://cloud.google.com/dataform",                    source: "cloud.google.com" },
      { title: "Migrate from Snowflake to BigQuery",    href: "https://cloud.google.com/bigquery/docs/migration/snowflake", source: "cloud.google.com" },
    ],
  },

  "m-monday-7": {
    meeting: {
      client: "Monday.com",
      title: "GKE Autopilot follow-up",
      date: "Apr 22, 2026",
      duration: "29 minutes",
      avatar: "#34A853",
      participants: ["Roy Maor (VP Platform)", "Tal Grinberg (SRE Lead)", "Noa Levi (SuperCloud)"],
    },
    internal: {
      confidence: 0.91,
      health: "hot",
      score: 91,
      wentWell: [
        "Client is ready to sign — Roy confirmed budget approval from CTO.",
        "Autopilot cost projections landed perfectly — 34% savings vs their current self-managed GKE.",
        "Tal was impressed by the bin-packing efficiency demo; asked for the notebook to share with his team.",
      ],
      couldImprove: [
        "Could have pushed for a firm signing date instead of 'within two weeks'.",
        "Didn't explore multi-cluster gateway needs — may surface during implementation.",
      ],
      upsell: [
        { name: "GKE Enterprise",      reason: "Roy mentioned multi-region plans for H2 — fleet management is a natural upsell." },
        { name: "Cloud Deploy",         reason: "Tal described a complex Jenkins-based CD pipeline — Cloud Deploy simplification pitch." },
      ],
      risks: [
        "Legal review on MSA could take 2–3 weeks — may push past Q2 close.",
      ],
      needs: {
        stated: ["Reduce Kubernetes ops burden", "Lower compute costs", "Improve scaling speed"],
        actual: ["Free SRE team for platform work", "Show cost savings to CTO for budget cycle", "De-risk Q3 multi-region expansion"],
      },
      actionItems: [
        { who: "Noa",    what: "Send Autopilot bin-packing notebook to Tal",                       due: "Apr 23" },
        { who: "Noa",    what: "Prepare MSA draft and send to legal",                               due: "Apr 25" },
        { who: "Roy",    what: "Confirm signing timeline with CTO",                                  due: "Apr 28" },
        { who: "Eitan",  what: "Coordinate commercial terms with Monday.com procurement",           due: "Apr 30" },
      ],
    },
    client: {
      subject: "Recap — GKE Autopilot follow-up (Apr 22)",
      greeting: "Hi Roy, Tal,",
      body: [
        "Short and sweet today — thanks for the focused session. Here's where we landed.",
        "**Discussion summary**\nWe reviewed the GKE Autopilot cost projections and confirmed a 34% savings estimate vs. your current self-managed setup. Tal validated the bin-packing efficiency numbers against your production workload profiles.",
        "**Key topics covered**\n• Cost projection: 34% savings on compute with Autopilot's optimized scheduling\n• Scaling performance: sub-30s pod scheduling for burst workloads\n• SRE impact: estimated 60% reduction in cluster maintenance toil\n• Timeline: targeting MSA completion within two weeks",
        "**Next steps**\n• I'll send the bin-packing demo notebook today.\n• MSA draft will be ready by Apr 25 for your legal team's review.\n• Roy, if you can confirm the signing timeline with your CTO, we can align on a go-live date.",
        "Excited to get this moving. Let me know if anything comes up.",
      ],
      signoff: "Best,\nNoa Levi\nSr. Cloud SE — SuperCloud",
    },
    references: [
      { title: "GKE Autopilot overview",                href: "https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview", source: "cloud.google.com" },
      { title: "GKE pricing",                            href: "https://cloud.google.com/kubernetes-engine/pricing",   source: "cloud.google.com" },
      { title: "GKE Enterprise — fleet management",     href: "https://cloud.google.com/kubernetes-engine/enterprise", source: "cloud.google.com" },
      { title: "Cloud Deploy for GKE",                   href: "https://cloud.google.com/deploy",                       source: "cloud.google.com" },
    ],
  },

  "m-wix-1": {
    meeting: {
      client: "Wix",
      title: "First introduction — AI infra",
      date: "Apr 21, 2026",
      duration: "32 minutes",
      avatar: "#F9AB00",
      participants: ["Matan Bordo (Dir. AI Platform)", "Noa Levi (SuperCloud)"],
    },
    internal: {
      confidence: 0.52,
      health: "cool",
      score: 64,
      wentWell: [
        "Good first impression — Matan was receptive to Gemini Flash positioning for their high-throughput use case.",
        "Identified their key pain: managing multiple model providers with no unified API layer.",
      ],
      couldImprove: [
        "Conversation stayed high-level — didn't get into specifics on current infrastructure or spend.",
        "Matan was guarded about competitive situation — likely evaluating Azure OpenAI simultaneously.",
        "Should have asked about their internal ML platform team size and roadmap.",
      ],
      upsell: [
        { name: "Vertex AI Endpoints",  reason: "They need unified model serving — natural entry point." },
        { name: "Gemini API",            reason: "High-volume, low-latency use case fits Gemini Flash perfectly." },
      ],
      risks: [
        "Early-stage — no clear buying signal yet.",
        "Likely evaluating multiple providers (Azure OpenAI hinted).",
        "Decision timeline unclear — 'sometime in Q3' is vague.",
      ],
      needs: {
        stated: ["Evaluate Gemini for content generation", "Unified model API", "Low latency at scale"],
        actual: ["Reduce dependency on single provider (OpenAI)", "Cost control as AI usage grows", "Internal platform team credibility"],
      },
      actionItems: [
        { who: "Noa",    what: "Share Gemini Flash benchmark vs GPT-4o-mini for their use case",   due: "Apr 25" },
        { who: "Noa",    what: "Send Vertex AI Endpoints one-pager",                                 due: "Apr 25" },
        { who: "Matan",  what: "Share current throughput requirements and latency SLOs",              due: "Apr 28" },
      ],
    },
    client: {
      subject: "Great meeting — Gemini + Vertex AI overview (Apr 21)",
      greeting: "Hi Matan,",
      body: [
        "Thanks for taking the time to chat today. Really enjoyed learning about what you're building on the AI platform side.",
        "**Discussion summary**\nWe discussed your current multi-model setup and the challenges around managing different provider APIs. I gave an overview of Vertex AI's unified endpoint approach and how Gemini Flash could fit your high-throughput content generation pipeline.",
        "**Key topics covered**\n• Your current multi-provider model serving architecture\n• Gemini Flash capabilities for high-throughput, low-latency inference\n• Vertex AI Endpoints as a unified serving layer\n• General timeline: evaluating options for Q3 decision",
        "**Next steps**\n• I'll send over a Gemini Flash benchmark comparison and a Vertex AI Endpoints overview by Apr 25.\n• If you can share your throughput requirements and latency SLOs, I can put together a more targeted proposal.\n• Happy to schedule a hands-on session with your team whenever you're ready.",
        "Looking forward to staying in touch.",
      ],
      signoff: "Best,\nNoa Levi\nSr. Cloud SE — SuperCloud",
    },
    references: [
      { title: "Gemini API overview",                    href: "https://cloud.google.com/vertex-ai/generative-ai/docs/gemini-api", source: "cloud.google.com" },
      { title: "Gemini Flash — speed and efficiency",    href: "https://cloud.google.com/vertex-ai/generative-ai/docs/models/gemini", source: "cloud.google.com" },
      { title: "Vertex AI Endpoints",                    href: "https://cloud.google.com/vertex-ai/docs/predictions/overview", source: "cloud.google.com" },
    ],
  },

  "m-aviv-2": {
    meeting: {
      client: "Aviv Capital",
      title: "Discovery call — algo trading desk",
      date: "Apr 14, 2026",
      duration: "52 minutes",
      avatar: "#EA4335",
      participants: ["Yael Ben-David (VP Eng)", "Oren Gilad (Head of Algo Trading)", "Noa Levi (SuperCloud)"],
    },
    internal: {
      confidence: 0.70,
      health: "warm",
      score: 78,
      wentWell: [
        "Uncovered the real pain — Bedrock latency in EU is costing them trading accuracy.",
        "Built good rapport with Oren who was initially skeptical of switching providers.",
        "Positioned Vertex AI as a multi-model hedge, not a lock-in replacement — resonated well.",
      ],
      couldImprove: [
        "Spent too long on product overview — should have jumped to their specific use case faster.",
        "Didn't quantify the business impact of latency ($ per ms of delay).",
        "Should have asked about their model evaluation framework upfront.",
      ],
      upsell: [
        { name: "Vertex AI Model Garden", reason: "They want Anthropic + Google models — Model Garden is the pitch." },
        { name: "Cloud Spanner",          reason: "Oren mentioned low-latency transactional DB needs for trade execution." },
      ],
      risks: [
        "Oren is influential but not the budget owner — need to get Yael's CTO involved.",
        "AWS relationship is deep — they have an Enterprise Discount Program.",
      ],
      needs: {
        stated: ["Sub-second inference from Europe", "Access to multiple models", "Reduce inference costs"],
        actual: ["Reduce dependency on AWS before contract renewal", "Prove to board they're optimizing AI spend", "Maintain trading desk SLAs during migration"],
      },
      actionItems: [
        { who: "Noa",    what: "Prepare regional latency comparison (eu-west4 vs us-east-1)",      due: "Apr 18" },
        { who: "Noa",    what: "Schedule technical deep-dive with Daniel from ML team",              due: "Apr 20" },
        { who: "Oren",   what: "Share current model serving architecture diagram",                   due: "Apr 17" },
        { who: "Yael",   what: "Introduce CTO for commercial discussion",                           due: "Apr 21" },
      ],
    },
    client: {
      subject: "Recap — discovery call, algo trading desk (Apr 14)",
      greeting: "Hi Yael, Oren,",
      body: [
        "Really enjoyed today's conversation. Thanks for being so open about your current setup and the challenges you're facing. Here's a quick summary.",
        "**Discussion summary**\nWe explored your algo trading desk's AI infrastructure, focusing on the latency challenges with your current Bedrock setup for European market coverage. We discussed how Vertex AI's regional deployment model and Model Garden could address both latency and multi-model flexibility.",
        "**Key topics covered**\n• Trading desk ML pipeline: model serving for real-time signals\n• EU latency pain: 1.8–2.2s p95 from us-east-1\n• Multi-model requirements: Anthropic Claude + Google Gemini\n• Cost structure: current ~$38K/mo on Bedrock inference",
        "**Next steps**\n• I'll prepare a detailed latency comparison between Vertex AI in europe-west4 and your current us-east-1 setup by Apr 18.\n• We'll schedule a technical deep-dive with your ML team for the following week.\n• Oren, if you can share your current architecture diagram, it'll help us map out the migration path.\n• Yael, a warm intro to your CTO for the commercial side would be the next step when you're ready.",
        "Talk soon!",
      ],
      signoff: "Best,\nNoa Levi\nSr. Cloud SE — SuperCloud",
    },
    references: [
      { title: "Vertex AI Model Garden — overview",              href: "https://cloud.google.com/model-garden",                    source: "cloud.google.com" },
      { title: "Regional endpoints for Vertex AI",               href: "https://cloud.google.com/vertex-ai/docs/general/locations", source: "cloud.google.com" },
      { title: "Anthropic Claude on Vertex AI",                   href: "https://cloud.google.com/vertex-ai/generative-ai/docs/partner-models/claude", source: "cloud.google.com" },
      { title: "Cloud Spanner overview",                          href: "https://cloud.google.com/spanner",                         source: "cloud.google.com" },
    ],
  },

  "m-pagaya-1": {
    meeting: {
      client: "Pagaya",
      title: "Cloud Spanner + Vertex briefing",
      date: "Apr 18, 2026",
      duration: "41 minutes",
      avatar: "#1A73E8",
      participants: ["Adi Navon (CTO)", "Tali Frenkel (Eng Manager)", "Noa Levi (SuperCloud)"],
    },
    internal: {
      confidence: 0.73,
      health: "warm",
      score: 80,
      wentWell: [
        "CTO attended personally — strong signal of interest.",
        "Spanner's global consistency story landed well for their multi-region credit scoring use case.",
        "Connected Vertex AI to their ML ops pain — they're doing manual model deployments today.",
      ],
      couldImprove: [
        "Didn't address their concern about Spanner pricing complexity — should prepare a clear TCO.",
        "Tali asked about Spanner's PostgreSQL interface compatibility — wasn't prepared with specifics.",
        "Should have probed more on their current database (CockroachDB) pain points.",
      ],
      upsell: [
        { name: "Vertex AI Pipelines",   reason: "Manual ML deployments — Pipelines would save their team 20+ hrs/week." },
        { name: "AlloyDB",               reason: "If Spanner pricing is a blocker, AlloyDB PostgreSQL is a fallback." },
        { name: "Cloud KMS",             reason: "Adi mentioned compliance with financial regulators — KMS + CMEK pitch." },
      ],
      risks: [
        "Spanner pricing may be a sticker shock — need to frame TCO vs. CockroachDB ops cost.",
        "Engineering team is stretched — migration capacity is limited until Q3.",
      ],
      needs: {
        stated: ["Globally consistent database", "Better ML deployment pipeline", "Regulatory compliance"],
        actual: ["Replace CockroachDB before scaling issues hit", "Reduce time-to-deploy for ML models", "Pass upcoming SOC2 + financial regulator audit"],
      },
      actionItems: [
        { who: "Noa",    what: "Prepare Spanner vs CockroachDB TCO comparison",                    due: "Apr 22" },
        { who: "Noa",    what: "Send Spanner PostgreSQL interface compatibility guide",             due: "Apr 22" },
        { who: "Lior",   what: "Schedule architecture review for Spanner + Vertex integration",    due: "Apr 25" },
        { who: "Tali",   what: "Share current DB schema and query patterns",                        due: "Apr 24" },
      ],
    },
    client: {
      subject: "Recap — Cloud Spanner + Vertex AI briefing (Apr 18)",
      greeting: "Hi Adi, Tali,",
      body: [
        "Thanks for the great conversation today. It was helpful to understand your infrastructure goals and the compliance requirements driving them.",
        "**Discussion summary**\nWe discussed how Cloud Spanner's globally consistent architecture fits your multi-region credit scoring platform, and explored Vertex AI Pipelines as a way to automate your current ML deployment workflow.",
        "**Key topics covered**\n• Multi-region database needs for credit scoring with strong consistency\n• Current CockroachDB setup and scaling concerns\n• ML deployment: manual process today, exploring automation\n• Regulatory compliance: SOC2 and financial regulator requirements",
        "**Next steps**\n• I'll send a Spanner vs CockroachDB TCO comparison and the PostgreSQL interface compatibility guide by Apr 22.\n• Lior from our solutions architecture team will schedule a deeper architecture review for the week of Apr 28.\n• Tali, if you can share your current DB schema and key query patterns, we can prepare a more targeted migration assessment.",
        "Looking forward to the next conversation.",
      ],
      signoff: "Best,\nNoa Levi\nSr. Cloud SE — SuperCloud",
    },
    references: [
      { title: "Cloud Spanner overview",                         href: "https://cloud.google.com/spanner",                          source: "cloud.google.com" },
      { title: "Spanner PostgreSQL interface",                   href: "https://cloud.google.com/spanner/docs/postgresql-interface", source: "cloud.google.com" },
      { title: "Cloud Spanner pricing",                          href: "https://cloud.google.com/spanner/pricing",                   source: "cloud.google.com" },
      { title: "Vertex AI Pipelines",                            href: "https://cloud.google.com/vertex-ai/docs/pipelines",          source: "cloud.google.com" },
      { title: "Cloud KMS — key management",                    href: "https://cloud.google.com/kms",                                source: "cloud.google.com" },
    ],
  },
};

window.SUMMARY = window.SUMMARIES["m-aviv-3"];
